use rdev::{Button as RdevButton, EventType, Key as RdevKey};
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone)]
pub enum KvmEvent {
    KeyPress(Key),
    KeyRelease(Key),
    ButtonPress(Button),
    ButtonRelease(Button),
    MouseMove { x: f64, y: f64 },
    Wheel { delta_x: i64, delta_y: i64 },
}

#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq)]
pub enum Button {
    Left,
    Right,
    Middle,
    Unknown(u8),
}

#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq)]
pub enum Key {
    Alt,
    AltGr,
    Backspace,
    CapsLock,
    ControlLeft,
    ControlRight,
    Delete,
    DownArrow,
    End,
    Escape,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    Home,
    LeftArrow,
    MetaLeft,
    MetaRight,
    PageDown,
    PageUp,
    Return,
    RightArrow,
    ShiftLeft,
    ShiftRight,
    Space,
    Tab,
    UpArrow,
    PrintScreen,
    ScrollLock,
    Pause,
    NumLock,
    BackQuote,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    Num0,
    Minus,
    Equal,
    KeyQ,
    KeyW,
    KeyE,
    KeyR,
    KeyT,
    KeyY,
    KeyU,
    KeyI,
    KeyO,
    KeyP,
    LeftBracket,
    RightBracket,
    KeyA,
    KeyS,
    KeyD,
    KeyF,
    KeyG,
    KeyH,
    KeyJ,
    KeyK,
    KeyL,
    SemiColon,
    Quote,
    BackSlash,
    IntlBackslash,
    KeyZ,
    KeyX,
    KeyC,
    KeyV,
    KeyB,
    KeyN,
    KeyM,
    Comma,
    Dot,
    Slash,
    Insert,
    KpReturn,
    KpMinus,
    KpPlus,
    KpMultiply,
    KpDivide,
    Kp0,
    Kp1,
    Kp2,
    Kp3,
    Kp4,
    Kp5,
    Kp6,
    Kp7,
    Kp8,
    Kp9,
    KpDelete,
    Function,
    Unknown(u32),
}

impl From<EventType> for KvmEvent {
    fn from(event: EventType) -> Self {
        match event {
            EventType::KeyPress(key) => KvmEvent::KeyPress(key.into()),
            EventType::KeyRelease(key) => KvmEvent::KeyRelease(key.into()),
            EventType::ButtonPress(btn) => KvmEvent::ButtonPress(btn.into()),
            EventType::ButtonRelease(btn) => KvmEvent::ButtonRelease(btn.into()),
            EventType::MouseMove { x, y } => KvmEvent::MouseMove { x, y },
            EventType::Wheel { delta_x, delta_y } => KvmEvent::Wheel { delta_x, delta_y },
        }
    }
}

impl From<KvmEvent> for EventType {
    fn from(event: KvmEvent) -> Self {
        match event {
            KvmEvent::KeyPress(key) => EventType::KeyPress(key.into()),
            KvmEvent::KeyRelease(key) => EventType::KeyRelease(key.into()),
            KvmEvent::ButtonPress(btn) => EventType::ButtonPress(btn.into()),
            KvmEvent::ButtonRelease(btn) => EventType::ButtonRelease(btn.into()),
            KvmEvent::MouseMove { x, y } => EventType::MouseMove { x, y },
            KvmEvent::Wheel { delta_x, delta_y } => EventType::Wheel { delta_x, delta_y },
        }
    }
}

impl From<RdevButton> for Button {
    fn from(btn: RdevButton) -> Self {
        match btn {
            RdevButton::Left => Button::Left,
            RdevButton::Right => Button::Right,
            RdevButton::Middle => Button::Middle,
            RdevButton::Unknown(u) => Button::Unknown(u),
        }
    }
}

impl From<Button> for RdevButton {
    fn from(btn: Button) -> Self {
        match btn {
            Button::Left => RdevButton::Left,
            Button::Right => RdevButton::Right,
            Button::Middle => RdevButton::Middle,
            Button::Unknown(u) => RdevButton::Unknown(u),
        }
    }
}

impl From<RdevKey> for Key {
    fn from(key: RdevKey) -> Self {
        match key {
            RdevKey::Alt => Key::Alt,
            RdevKey::AltGr => Key::AltGr,
            RdevKey::Backspace => Key::Backspace,
            RdevKey::CapsLock => Key::CapsLock,
            RdevKey::ControlLeft => Key::ControlLeft,
            RdevKey::ControlRight => Key::ControlRight,
            RdevKey::Delete => Key::Delete,
            RdevKey::DownArrow => Key::DownArrow,
            RdevKey::End => Key::End,
            RdevKey::Escape => Key::Escape,
            RdevKey::F1 => Key::F1,
            RdevKey::F2 => Key::F2,
            RdevKey::F3 => Key::F3,
            RdevKey::F4 => Key::F4,
            RdevKey::F5 => Key::F5,
            RdevKey::F6 => Key::F6,
            RdevKey::F7 => Key::F7,
            RdevKey::F8 => Key::F8,
            RdevKey::F9 => Key::F9,
            RdevKey::F10 => Key::F10,
            RdevKey::F11 => Key::F11,
            RdevKey::F12 => Key::F12,
            RdevKey::Home => Key::Home,
            RdevKey::LeftArrow => Key::LeftArrow,
            RdevKey::MetaLeft => Key::MetaLeft,
            RdevKey::MetaRight => Key::MetaRight,
            RdevKey::PageDown => Key::PageDown,
            RdevKey::PageUp => Key::PageUp,
            RdevKey::Return => Key::Return,
            RdevKey::RightArrow => Key::RightArrow,
            RdevKey::ShiftLeft => Key::ShiftLeft,
            RdevKey::ShiftRight => Key::ShiftRight,
            RdevKey::Space => Key::Space,
            RdevKey::Tab => Key::Tab,
            RdevKey::UpArrow => Key::UpArrow,
            RdevKey::PrintScreen => Key::PrintScreen,
            RdevKey::ScrollLock => Key::ScrollLock,
            RdevKey::Pause => Key::Pause,
            RdevKey::NumLock => Key::NumLock,
            RdevKey::BackQuote => Key::BackQuote,
            RdevKey::Num1 => Key::Num1,
            RdevKey::Num2 => Key::Num2,
            RdevKey::Num3 => Key::Num3,
            RdevKey::Num4 => Key::Num4,
            RdevKey::Num5 => Key::Num5,
            RdevKey::Num6 => Key::Num6,
            RdevKey::Num7 => Key::Num7,
            RdevKey::Num8 => Key::Num8,
            RdevKey::Num9 => Key::Num9,
            RdevKey::Num0 => Key::Num0,
            RdevKey::Minus => Key::Minus,
            RdevKey::Equal => Key::Equal,
            RdevKey::KeyQ => Key::KeyQ,
            RdevKey::KeyW => Key::KeyW,
            RdevKey::KeyE => Key::KeyE,
            RdevKey::KeyR => Key::KeyR,
            RdevKey::KeyT => Key::KeyT,
            RdevKey::KeyY => Key::KeyY,
            RdevKey::KeyU => Key::KeyU,
            RdevKey::KeyI => Key::KeyI,
            RdevKey::KeyO => Key::KeyO,
            RdevKey::KeyP => Key::KeyP,
            RdevKey::LeftBracket => Key::LeftBracket,
            RdevKey::RightBracket => Key::RightBracket,
            RdevKey::KeyA => Key::KeyA,
            RdevKey::KeyS => Key::KeyS,
            RdevKey::KeyD => Key::KeyD,
            RdevKey::KeyF => Key::KeyF,
            RdevKey::KeyG => Key::KeyG,
            RdevKey::KeyH => Key::KeyH,
            RdevKey::KeyJ => Key::KeyJ,
            RdevKey::KeyK => Key::KeyK,
            RdevKey::KeyL => Key::KeyL,
            RdevKey::SemiColon => Key::SemiColon,
            RdevKey::Quote => Key::Quote,
            RdevKey::BackSlash => Key::BackSlash,
            RdevKey::IntlBackslash => Key::IntlBackslash,
            RdevKey::KeyZ => Key::KeyZ,
            RdevKey::KeyX => Key::KeyX,
            RdevKey::KeyC => Key::KeyC,
            RdevKey::KeyV => Key::KeyV,
            RdevKey::KeyB => Key::KeyB,
            RdevKey::KeyN => Key::KeyN,
            RdevKey::KeyM => Key::KeyM,
            RdevKey::Comma => Key::Comma,
            RdevKey::Dot => Key::Dot,
            RdevKey::Slash => Key::Slash,
            RdevKey::Insert => Key::Insert,
            RdevKey::KpReturn => Key::KpReturn,
            RdevKey::KpMinus => Key::KpMinus,
            RdevKey::KpPlus => Key::KpPlus,
            RdevKey::KpMultiply => Key::KpMultiply,
            RdevKey::KpDivide => Key::KpDivide,
            RdevKey::Kp0 => Key::Kp0,
            RdevKey::Kp1 => Key::Kp1,
            RdevKey::Kp2 => Key::Kp2,
            RdevKey::Kp3 => Key::Kp3,
            RdevKey::Kp4 => Key::Kp4,
            RdevKey::Kp5 => Key::Kp5,
            RdevKey::Kp6 => Key::Kp6,
            RdevKey::Kp7 => Key::Kp7,
            RdevKey::Kp8 => Key::Kp8,
            RdevKey::Kp9 => Key::Kp9,
            RdevKey::KpDelete => Key::KpDelete,
            RdevKey::Function => Key::Function,
            RdevKey::Unknown(u) => Key::Unknown(u),
        }
    }
}

impl From<Key> for RdevKey {
    fn from(key: Key) -> Self {
        match key {
            Key::Alt => RdevKey::Alt,
            Key::AltGr => RdevKey::AltGr,
            Key::Backspace => RdevKey::Backspace,
            Key::CapsLock => RdevKey::CapsLock,
            Key::ControlLeft => RdevKey::ControlLeft,
            Key::ControlRight => RdevKey::ControlRight,
            Key::Delete => RdevKey::Delete,
            Key::DownArrow => RdevKey::DownArrow,
            Key::End => RdevKey::End,
            Key::Escape => RdevKey::Escape,
            Key::F1 => RdevKey::F1,
            Key::F2 => RdevKey::F2,
            Key::F3 => RdevKey::F3,
            Key::F4 => RdevKey::F4,
            Key::F5 => RdevKey::F5,
            Key::F6 => RdevKey::F6,
            Key::F7 => RdevKey::F7,
            Key::F8 => RdevKey::F8,
            Key::F9 => RdevKey::F9,
            Key::F10 => RdevKey::F10,
            Key::F11 => RdevKey::F11,
            Key::F12 => RdevKey::F12,
            Key::Home => RdevKey::Home,
            Key::LeftArrow => RdevKey::LeftArrow,
            Key::MetaLeft => RdevKey::MetaLeft,
            Key::MetaRight => RdevKey::MetaRight,
            Key::PageDown => RdevKey::PageDown,
            Key::PageUp => RdevKey::PageUp,
            Key::Return => RdevKey::Return,
            Key::RightArrow => RdevKey::RightArrow,
            Key::ShiftLeft => RdevKey::ShiftLeft,
            Key::ShiftRight => RdevKey::ShiftRight,
            Key::Space => RdevKey::Space,
            Key::Tab => RdevKey::Tab,
            Key::UpArrow => RdevKey::UpArrow,
            Key::PrintScreen => RdevKey::PrintScreen,
            Key::ScrollLock => RdevKey::ScrollLock,
            Key::Pause => RdevKey::Pause,
            Key::NumLock => RdevKey::NumLock,
            Key::BackQuote => RdevKey::BackQuote,
            Key::Num1 => RdevKey::Num1,
            Key::Num2 => RdevKey::Num2,
            Key::Num3 => RdevKey::Num3,
            Key::Num4 => RdevKey::Num4,
            Key::Num5 => RdevKey::Num5,
            Key::Num6 => RdevKey::Num6,
            Key::Num7 => RdevKey::Num7,
            Key::Num8 => RdevKey::Num8,
            Key::Num9 => RdevKey::Num9,
            Key::Num0 => RdevKey::Num0,
            Key::Minus => RdevKey::Minus,
            Key::Equal => RdevKey::Equal,
            Key::KeyQ => RdevKey::KeyQ,
            Key::KeyW => RdevKey::KeyW,
            Key::KeyE => RdevKey::KeyE,
            Key::KeyR => RdevKey::KeyR,
            Key::KeyT => RdevKey::KeyT,
            Key::KeyY => RdevKey::KeyY,
            Key::KeyU => RdevKey::KeyU,
            Key::KeyI => RdevKey::KeyI,
            Key::KeyO => RdevKey::KeyO,
            Key::KeyP => RdevKey::KeyP,
            Key::LeftBracket => RdevKey::LeftBracket,
            Key::RightBracket => RdevKey::RightBracket,
            Key::KeyA => RdevKey::KeyA,
            Key::KeyS => RdevKey::KeyS,
            Key::KeyD => RdevKey::KeyD,
            Key::KeyF => RdevKey::KeyF,
            Key::KeyG => RdevKey::KeyG,
            Key::KeyH => RdevKey::KeyH,
            Key::KeyJ => RdevKey::KeyJ,
            Key::KeyK => RdevKey::KeyK,
            Key::KeyL => RdevKey::KeyL,
            Key::SemiColon => RdevKey::SemiColon,
            Key::Quote => RdevKey::Quote,
            Key::BackSlash => RdevKey::BackSlash,
            Key::IntlBackslash => RdevKey::IntlBackslash,
            Key::KeyZ => RdevKey::KeyZ,
            Key::KeyX => RdevKey::KeyX,
            Key::KeyC => RdevKey::KeyC,
            Key::KeyV => RdevKey::KeyV,
            Key::KeyB => RdevKey::KeyB,
            Key::KeyN => RdevKey::KeyN,
            Key::KeyM => RdevKey::KeyM,
            Key::Comma => RdevKey::Comma,
            Key::Dot => RdevKey::Dot,
            Key::Slash => RdevKey::Slash,
            Key::Insert => RdevKey::Insert,
            Key::KpReturn => RdevKey::KpReturn,
            Key::KpMinus => RdevKey::KpMinus,
            Key::KpPlus => RdevKey::KpPlus,
            Key::KpMultiply => RdevKey::KpMultiply,
            Key::KpDivide => RdevKey::KpDivide,
            Key::Kp0 => RdevKey::Kp0,
            Key::Kp1 => RdevKey::Kp1,
            Key::Kp2 => RdevKey::Kp2,
            Key::Kp3 => RdevKey::Kp3,
            Key::Kp4 => RdevKey::Kp4,
            Key::Kp5 => RdevKey::Kp5,
            Key::Kp6 => RdevKey::Kp6,
            Key::Kp7 => RdevKey::Kp7,
            Key::Kp8 => RdevKey::Kp8,
            Key::Kp9 => RdevKey::Kp9,
            Key::KpDelete => RdevKey::KpDelete,
            Key::Function => RdevKey::Function,
            Key::Unknown(u) => RdevKey::Unknown(u),
        }
    }
}
